# Generated by Django 4.1.2 on 2022-10-25 07:53

import crixita.apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('t_type', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['t_type'],
            },
            bases=(crixita.apps.common.models.SlugMixin, models.Model),
        ),
    ]
