# Generated by Django 4.1.2 on 2022-11-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='t_type',
        ),
        migrations.AddField(
            model_name='tag',
            name='fathers',
            field=models.ManyToManyField(blank=True, related_name='children', to='common.tag'),
        ),
    ]
